on: push

jobs: 
  first-job:
    name: Job 1
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version

  second-job:
    name: Job 2
    runs-on: windows-latest
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
          
      
