
name: Node Continuous Integration
on: push

jobs: 
  build-node-ubuntu:
    name: Builld Node - Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: dir
      - run: npm install
      - run: node app.js

  build-node-windows:
    name: Build node - Windows
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: dir
      - run: npm install
      - run: node app.js